######################################################################
# Automatically generated by qmake (2.01a) ?? 6? 13 19:42:08 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
QT += phonon
HEADERS += mainwindow.h qdynamicbutton.h
SOURCES += main.cpp mainwindow.cpp qdynamicbutton.cpp
