######################################################################
# Automatically generated by qmake (2.01a) ?? 6? 13 01:43:33 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h qdynamicbutton.h
SOURCES += main.cpp mainwindow.cpp qdynamicbutton.cpp
