######################################################################
# Automatically generated by qmake (2.01a) ?? 6? 24 01:59:07 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
QT += phonon
HEADERS += mainwindow.h myitem.h newWindow.h
SOURCES += main.cpp mainwindow.cpp myitem.cpp newWindow.cpp
