######################################################################
# Automatically generated by qmake (2.01a) ?? 6? 13 21:41:03 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
QT += phonon
HEADERS += mainwindow.h myitem.h
SOURCES += main.cpp mainwindow.cpp myitem.cpp
