######################################################################
# Automatically generated by qmake (2.01a) ?? 6? 13 19:02:07 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
QT += phonon
HEADERS += mainwindow.h mywidget.h
SOURCES += main.cpp mainwindow.cpp mywidget.cpp
