######################################################################
# Automatically generated by qmake (2.01a) ?? 5? 20 10:35:16 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
QT += phonon
HEADERS += mainwindow.h mywidget.h
SOURCES += main.cpp mainwindow.cpp mywidget.cpp
